export * from "./layout/footer";
import logo from "./logo/logo.png";
import bgBannerImg from "./home/bg.png";
import news1 from "./home/news/n1.png";
import news2 from "./home/news/n2.png";
import news3 from "./home/news/n3.png";
import i1 from "./home/photos/i1.png";
export { logo, bgBannerImg };
export { news1 };
export { news2 };
export { news3 };
export { i1 };
